name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - master

jobs:
  sbt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # see https://github.com/actions/cache/blob/master/examples.md#scala---sbt
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./scripts/ci
